In [1]:
import pandas as pd
import numpy as np

a. From given dataset, clean the table with these criteria:
- Employee_ID is unique, please make sure this criterion is fulfilled
- Create a standard for name, gender, edu_lvl, job category, age, score, number phone,
and domicile column
- You can use your creativity to improve the table to be cleaner.
- Use python language. Please send us the script. You can use Jupyter
Notebook, or any IDE you comfortable with.

In [2]:
dataset1 = pd.read_excel("D:\Kerja\Dattabot\dataset_jul_2021.xlsx",'dataset1')

In [3]:
dataset2 = pd.read_excel("D:\Kerja\Dattabot\dataset_jul_2021.xlsx",'dataset2')

In [4]:
dataset3 = pd.read_excel("D:\Kerja\Dattabot\dataset_jul_2021.xlsx",'dataset3')

In [5]:
dataset = pd.concat([dataset1,dataset2,dataset3], ignore_index=True)

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Employee_ID        930 non-null    int64 
 1   Name               930 non-null    object
 2   GENDER             930 non-null    object
 3   EDU_LVL            930 non-null    object
 4   JOB_CATEGORY       930 non-null    object
 5   AGE                930 non-null    int64 
 6   Score              920 non-null    object
 7   Phone Number       930 non-null    int64 
 8   Domicile_Province  930 non-null    object
dtypes: int64(3), object(6)
memory usage: 65.5+ KB


In [7]:
data = dataset.rename(columns={"Employee_ID":"Employee_Id", "GENDER":"Gender", "EDU_LVL":"Edu_Level", "JOB_CATEGORY":"Job_Category", "AGE":"Age", "Phone Number":"Phone_Number"})

In [8]:
data.head()

Employee_Id             Name Gender Edu_Level              Job_Category  \
0            1      Claire Gute      M        S1  Functional Expert Band 2   
1            2  Darrin Van Huff      M        S2                   Manager   
2            3   Sean O'Donnell   Male      SLTA                     Staff   
3            4  Brosina Hoffman      M        S2                   Manager   
4            5     Andrew Allen      F        S1                   Trainee   

   Age  Score  Phone_Number Domicile_Province  
0   37   3.98  628315242420       DKI Jakarta  
1   42   4.15   85246790036           Jakarta  
2   48   3.98   85246833311               JKT  
3   50   3.23   85246990032         West Java  
4   20   -      85247028027        Jawa Barat

In [9]:
for i in range(len(data)):
    if data.loc[i,'Score']==' -   ':
        data.loc[i,'Score']='0'

In [10]:
data.Score.unique()

array([3.98, 4.15, 3.23, '0', 4.66, 4.71, 4.05, 4.86, 3.76, 3.42, 4.07,
       4.29, 4, 3.83, 4.26, 3.9, 4.14, 3.96, 4.02, 3.36, 3.81, 4.04, 5,
       3.82, 3.05, 4.55, 3.87, 3.68, 3.51, 3.92, 4.52, 4.27, 3.33, 4.31,
       4.44, 3.71, nan, 4.22, 3.74, 3.89, 4.4, 3.93, 4.54, 4.13, 4.03,
       4.33, 3.73, 3.55, 4.08, 4.11, 3.86, 3.75, 3.63, 3.62, 3.31, 4.12,
       3.85, 3.34, 4.06, 3.01, 3.91, 4.2, 3.69, 4.37, 3.14, 3.58, 4.7,
       4.34, 4.6, 4.23, 3.53, 3.6, 3.97, 4.21, 3.44, 3.56, 4.01, 2.98,
       4.43, 3.67, 4.41, 4.81, 4.64, 4.35, 4.73, 3.52, 3.07, 4.38, 4.53,
       4.49, 3.77, 3.72, 2.35, 3.15, 2.67, 3.41, 4.19, 4.1, 3.79, 4.92,
       3.28, 4.39, 3.18, 3.66, 3.43, 3.61, 4.56, 4.67, 4.16, 3.02, 4.62,
       4.99, 4.69, 4.32, 2.95, 4.51, 3.99, 4.76, 3.25, 2.93, 4.17, 2.63,
       3.8, 3.2, 4.09, 3.5, 3.3, 3.88, 4.96, 4.74, 4.18, 3.78, 3.29, 3.48,
       3.54, 3.94, 4.25, 3.84, 3.35, 3.49, 4.87, 4.47, 4.61, 3.47, 3.7,
       3.11, 3.22, 3.03, 3.27, 3.57, 3.12, 3.17, 3.39, 4.36

In [11]:
data['Score']=data['Score'].astype(np.float64)

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Employee_Id        930 non-null    int64  
 1   Name               930 non-null    object 
 2   Gender             930 non-null    object 
 3   Edu_Level          930 non-null    object 
 4   Job_Category       930 non-null    object 
 5   Age                930 non-null    int64  
 6   Score              920 non-null    float64
 7   Phone_Number       930 non-null    int64  
 8   Domicile_Province  930 non-null    object 
dtypes: float64(1), int64(3), object(5)
memory usage: 65.5+ KB


In [13]:
data.Score.unique()

array([3.98, 4.15, 3.23, 0.  , 4.66, 4.71, 4.05, 4.86, 3.76, 3.42, 4.07,
       4.29, 4.  , 3.83, 4.26, 3.9 , 4.14, 3.96, 4.02, 3.36, 3.81, 4.04,
       5.  , 3.82, 3.05, 4.55, 3.87, 3.68, 3.51, 3.92, 4.52, 4.27, 3.33,
       4.31, 4.44, 3.71,  nan, 4.22, 3.74, 3.89, 4.4 , 3.93, 4.54, 4.13,
       4.03, 4.33, 3.73, 3.55, 4.08, 4.11, 3.86, 3.75, 3.63, 3.62, 3.31,
       4.12, 3.85, 3.34, 4.06, 3.01, 3.91, 4.2 , 3.69, 4.37, 3.14, 3.58,
       4.7 , 4.34, 4.6 , 4.23, 3.53, 3.6 , 3.97, 4.21, 3.44, 3.56, 4.01,
       2.98, 4.43, 3.67, 4.41, 4.81, 4.64, 4.35, 4.73, 3.52, 3.07, 4.38,
       4.53, 4.49, 3.77, 3.72, 2.35, 3.15, 2.67, 3.41, 4.19, 4.1 , 3.79,
       4.92, 3.28, 4.39, 3.18, 3.66, 3.43, 3.61, 4.56, 4.67, 4.16, 3.02,
       4.62, 4.99, 4.69, 4.32, 2.95, 4.51, 3.99, 4.76, 3.25, 2.93, 4.17,
       2.63, 3.8 , 3.2 , 4.09, 3.5 , 3.3 , 3.88, 4.96, 4.74, 4.18, 3.78,
       3.29, 3.48, 3.54, 3.94, 4.25, 3.84, 3.35, 3.49, 4.87, 4.47, 4.61,
       3.47, 3.7 , 3.11, 3.22, 3.03, 3.27, 3.57, 3.

In [14]:
data['Score']=data['Score'].replace(np.nan,0)

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Employee_Id        930 non-null    int64  
 1   Name               930 non-null    object 
 2   Gender             930 non-null    object 
 3   Edu_Level          930 non-null    object 
 4   Job_Category       930 non-null    object 
 5   Age                930 non-null    int64  
 6   Score              930 non-null    float64
 7   Phone_Number       930 non-null    int64  
 8   Domicile_Province  930 non-null    object 
dtypes: float64(1), int64(3), object(5)
memory usage: 65.5+ KB


In [16]:
data.Score.unique()

array([3.98, 4.15, 3.23, 0.  , 4.66, 4.71, 4.05, 4.86, 3.76, 3.42, 4.07,
       4.29, 4.  , 3.83, 4.26, 3.9 , 4.14, 3.96, 4.02, 3.36, 3.81, 4.04,
       5.  , 3.82, 3.05, 4.55, 3.87, 3.68, 3.51, 3.92, 4.52, 4.27, 3.33,
       4.31, 4.44, 3.71, 4.22, 3.74, 3.89, 4.4 , 3.93, 4.54, 4.13, 4.03,
       4.33, 3.73, 3.55, 4.08, 4.11, 3.86, 3.75, 3.63, 3.62, 3.31, 4.12,
       3.85, 3.34, 4.06, 3.01, 3.91, 4.2 , 3.69, 4.37, 3.14, 3.58, 4.7 ,
       4.34, 4.6 , 4.23, 3.53, 3.6 , 3.97, 4.21, 3.44, 3.56, 4.01, 2.98,
       4.43, 3.67, 4.41, 4.81, 4.64, 4.35, 4.73, 3.52, 3.07, 4.38, 4.53,
       4.49, 3.77, 3.72, 2.35, 3.15, 2.67, 3.41, 4.19, 4.1 , 3.79, 4.92,
       3.28, 4.39, 3.18, 3.66, 3.43, 3.61, 4.56, 4.67, 4.16, 3.02, 4.62,
       4.99, 4.69, 4.32, 2.95, 4.51, 3.99, 4.76, 3.25, 2.93, 4.17, 2.63,
       3.8 , 3.2 , 4.09, 3.5 , 3.3 , 3.88, 4.96, 4.74, 4.18, 3.78, 3.29,
       3.48, 3.54, 3.94, 4.25, 3.84, 3.35, 3.49, 4.87, 4.47, 4.61, 3.47,
       3.7 , 3.11, 3.22, 3.03, 3.27, 3.57, 3.12, 3.

In [17]:
data.duplicated(subset=['Employee_Id'])

0      False
1      False
2      False
3      False
4      False
       ...  
925    False
926    False
927    False
928    False
929    False
Length: 930, dtype: bool

In [18]:
data.Name.unique()

array(['Claire Gute', 'Darrin Van Huff', "Sean O'Donnell",
       'Brosina Hoffman', 'Andrew Allen', 'Irene Maddox', 'Harold Pawlan',
       'Pete Kriz', 'Alejandro Grove', 'Zuschuss Donatelli', 'Ken Black',
       'Sandra Flanagan', 'Emily Burns', 'Eric Hoffmann',
       'Tracy Blumstein', 'Matt Abelman%', 'Gene Hale,,', 'Steve Nguyen!',
       'Linda Cazamias', 'Ruben Ausman', 'Erin Smith', 'Odella Nelson',
       "Patrick O'Donnell", 'Lena Hernandez', 'Darren Powers',
       'Janet Molinari', 'Ted Butterfield', 'Kunst Miller',
       'Paul Stevenson', 'Brendan Sweed', 'Karen Daniels',
       'Henry MacAllister', 'Joel Eaton', 'Ken Brennan',
       'Stewart Carmichael', 'Duane Noonan', 'Julie Creighton',
       'Christopher Schild', 'Paul Gonzalez', 'Gary Mitchum', 'Jim Sink',
       'Karl Braun', 'Roger Barcio', 'Parhena Norris', 'Katherine Ducich',
       'Elpida Rittenbach', 'Rick Bensley', 'Gary Zandusky',
       'Lena Cacioppo', 'Janet Martin', 'Pete Armstrong', 'Cynthia Voltz',

In [19]:
import re

In [20]:
for i in range(len(data)):
    data.loc[i,'Name']=re.sub(r"\W+|_", " ",data.loc[i,"Name"])

In [21]:
data.Name.unique()

array(['Claire Gute', 'Darrin Van Huff', 'Sean O Donnell',
       'Brosina Hoffman', 'Andrew Allen', 'Irene Maddox', 'Harold Pawlan',
       'Pete Kriz', 'Alejandro Grove', 'Zuschuss Donatelli', 'Ken Black',
       'Sandra Flanagan', 'Emily Burns', 'Eric Hoffmann',
       'Tracy Blumstein', 'Matt Abelman ', 'Gene Hale ', 'Steve Nguyen ',
       'Linda Cazamias', 'Ruben Ausman', 'Erin Smith', 'Odella Nelson',
       'Patrick O Donnell', 'Lena Hernandez', 'Darren Powers',
       'Janet Molinari', 'Ted Butterfield', 'Kunst Miller',
       'Paul Stevenson', 'Brendan Sweed', 'Karen Daniels',
       'Henry MacAllister', 'Joel Eaton', 'Ken Brennan',
       'Stewart Carmichael', 'Duane Noonan', 'Julie Creighton',
       'Christopher Schild', 'Paul Gonzalez', 'Gary Mitchum', 'Jim Sink',
       'Karl Braun', 'Roger Barcio', 'Parhena Norris', 'Katherine Ducich',
       'Elpida Rittenbach', 'Rick Bensley', 'Gary Zandusky',
       'Lena Cacioppo', 'Janet Martin', 'Pete Armstrong', 'Cynthia Voltz',


In [22]:
data.Gender.unique()

array(['M', 'Male', 'F', 'Pria', 'Man', 'Laki-laki', 'Perempuan',
       'Wanita', 'Female'], dtype=object)

In [23]:
for i in range(len(data)):
    if data.loc[i,'Gender']=='M' or data.loc[i,'Gender']=='Pria' or data.loc[i,'Gender']=='Laki-laki' or data.loc[i,'Gender']=='Man':
        data.loc[i,'Gender']='Male'
    elif data.loc[i,'Gender']=='F' or data.loc[i,'Gender']=='Perempuan' or data.loc[i,'Gender']=='Wanita':
        data.loc[i,'Gender']='Female'

In [24]:
data.Edu_Level.unique()

array(['S1', 'S2', 'SLTA', 'D3', 'SMA', 'D1', 'D4'], dtype=object)

In [25]:
for i in range(len(data)):
    if data.loc[i,'Edu_Level']=='SMA':
        data.loc[i,'Edu_Level']='SLTA'

In [26]:
data.Job_Category.unique()

array(['Functional Expert Band 2', 'Manager', 'Staff', 'Trainee',
       'Supervisor', 'Senior Staff Band 2', 'Senior Staff Band 3',
       'Secretary', 'Functional Expert Band 3', 'Senior Vice President',
       'Vice President', 'Senior Staff Band 5'], dtype=object)

I use the assumption that:
1. Manager is included in the Functinal expert band 2.
2. Supervisor is included in the Functinal expert band 3.
3. Secretary is included in the senior staff of band 2.
4. Staff is included in the senior staff band 3.
5. Trainee is included in the senior staff of the band 5.

In [27]:
for i in range(len(data)):
    if data.loc[i,'Job_Category']=='Manager':
        data.loc[i,'Job_Category']='Functional Expert Band 2'
    elif data.loc[i,'Job_Category']=='Supervisor':
        data.loc[i,'Job_Category']='Functional Expert Band 3'
    elif data.loc[i,'Job_Category']=='Secretary':
        data.loc[i,'Job_Category']='Senior Staff Band 2'
    elif data.loc[i,'Job_Category']=='Staff':
        data.loc[i,'Job_Category']='Senior Staff Band 3'
    elif data.loc[i,'Job_Category']=='Trainee':
        data.loc[i,'Job_Category']='Senior Staff Band 5'

In [28]:
data.Age.unique()

array([37, 42, 48, 50, 20, 43, 27, 26, 32, 41, 40, 29, 31, 44, 35, 24, 34,
       49, 47, 46, 54, 33, 45, 52, 38, 55, 28, 25, 39, 23, 36, 30, 53, 51,
       22], dtype=int64)

In [29]:
data.Score.unique()

array([3.98, 4.15, 3.23, 0.  , 4.66, 4.71, 4.05, 4.86, 3.76, 3.42, 4.07,
       4.29, 4.  , 3.83, 4.26, 3.9 , 4.14, 3.96, 4.02, 3.36, 3.81, 4.04,
       5.  , 3.82, 3.05, 4.55, 3.87, 3.68, 3.51, 3.92, 4.52, 4.27, 3.33,
       4.31, 4.44, 3.71, 4.22, 3.74, 3.89, 4.4 , 3.93, 4.54, 4.13, 4.03,
       4.33, 3.73, 3.55, 4.08, 4.11, 3.86, 3.75, 3.63, 3.62, 3.31, 4.12,
       3.85, 3.34, 4.06, 3.01, 3.91, 4.2 , 3.69, 4.37, 3.14, 3.58, 4.7 ,
       4.34, 4.6 , 4.23, 3.53, 3.6 , 3.97, 4.21, 3.44, 3.56, 4.01, 2.98,
       4.43, 3.67, 4.41, 4.81, 4.64, 4.35, 4.73, 3.52, 3.07, 4.38, 4.53,
       4.49, 3.77, 3.72, 2.35, 3.15, 2.67, 3.41, 4.19, 4.1 , 3.79, 4.92,
       3.28, 4.39, 3.18, 3.66, 3.43, 3.61, 4.56, 4.67, 4.16, 3.02, 4.62,
       4.99, 4.69, 4.32, 2.95, 4.51, 3.99, 4.76, 3.25, 2.93, 4.17, 2.63,
       3.8 , 3.2 , 4.09, 3.5 , 3.3 , 3.88, 4.96, 4.74, 4.18, 3.78, 3.29,
       3.48, 3.54, 3.94, 4.25, 3.84, 3.35, 3.49, 4.87, 4.47, 4.61, 3.47,
       3.7 , 3.11, 3.22, 3.03, 3.27, 3.57, 3.12, 3.

In [30]:
data.Phone_Number.unique()

array([ 628315242420,   85246790036,   85246833311,   85246990032,
         85247028027,   85247198103, 6285247276106, 6285247353711,
       6285247484084, 6285247594109, 6285247668025, 6285247719140,
       6285247884057,   85247990049,   85247919140,   85247977095,
         85247975080,   85247977041,   85247960540,  628315232935,
         85246755122,   85246848185,   85246919901,   85247047150,
         85247110024, 6285247212180, 6285247390004, 6285247460610,
       6285247585234, 6285247622153, 6285247710009, 6285247849201,
         85247938109,   85247977070,   85247935601,   85247994122,
         85247927707,   85247960623,  628315229203,   85246755901,
         85246877095,   85246990036,   85247055407,   85247197206,
       6285247210009, 6285247394122, 6285247455106, 6285247560610,
       6285247655901, 6285247780013, 6285247828205,   85247960462,
         85247910035,   85247950322,   85247943229,   85247998103,
         85247937620,   85247919805,  628315277041,   85246761

In [31]:
for i in range(len(data)):
    if int(str(data.loc[i,'Phone_Number'])[:1])==8:
        data.loc[i,'Phone_Number']=int('62'+str(data.loc[i,'Phone_Number']))

In [32]:
data.Domicile_Province.unique()

array(['DKI Jakarta', 'Jakarta', 'JKT', 'West Java', 'Jawa Barat',
       'Jabar', 'Bandung', 'Jakarta Selatan', 'South Jakarta',
       'East Jakarta', 'Purwokerto', 'Purwakarta', 'Yogyakarta', 'DIY',
       'Depok', 'Bogor', 'Bekasi', 'Tangerang Selatan', 'Kalideres',
       'Sukabumi', 'Bali', 'Denpasar'], dtype=object)

In [33]:
for i in range(len(data)):
    if data.loc[i,'Domicile_Province']=='Jakarta' or data.loc[i,'Domicile_Province']=='JKT' or data.loc[i,'Domicile_Province']=='Jakarta Selatan' or data.loc[i,'Domicile_Province']=='South Jakarta' or data.loc[i,'Domicile_Province']=='East Jakarta' or data.loc[i,'Domicile_Province']=='Kalideres':
        data.loc[i,'Domicile_Province']='DKI Jakarta'
    elif data.loc[i,'Domicile_Province']=='West Java' or data.loc[i,'Domicile_Province']=='Jabar' or data.loc[i,'Domicile_Province']=='Bandung' or data.loc[i,'Domicile_Province']=='Purwakarta' or data.loc[i,'Domicile_Province']=='Depok' or data.loc[i,'Domicile_Province']=='Bogor' or data.loc[i,'Domicile_Province']=='Bekasi' or data.loc[i,'Domicile_Province']=='Tangerang Selatan' or data.loc[i,'Domicile_Province']=='Sukabumi':
        data.loc[i,'Domicile_Province']='Jawa Barat'
    elif data.loc[i,'Domicile_Province']=='Purwokerto':
        data.loc[i,'Domicile_Province']='Jawa Tengah'
    elif data.loc[i,'Domicile_Province']=='Yogyakarta' or data.loc[i,'Domicile_Province']=='DIY':
        data.loc[i,'Domicile_Province']='DI Yogyakarta'
    elif data.loc[i,'Domicile_Province']=='Denpasar':
        data.loc[i,'Domicile_Province']='Bali'

In [34]:
data.sample(10)

Employee_Id            Name  Gender Edu_Level              Job_Category  \
163          164    Julia Dunbar    Male        S2       Senior Staff Band 3   
53            54  Pete Armstrong  Female        S1  Functional Expert Band 3   
20            21      Erin Smith  Female        D3  Functional Expert Band 3   
721          722   Cindy Stewart    Male        S1  Functional Expert Band 2   
287          288    Meg O Connel    Male        S2       Senior Staff Band 3   
809          810     Shaun Weien    Male        S1  Functional Expert Band 3   
409          410   Guy Armstrong  Female        S1  Functional Expert Band 3   
723          724  Jessica Myrick    Male        S1  Functional Expert Band 3   
107          108     David Smith  Female      SLTA       Senior Staff Band 3   
561          562      Joel Eaton    Male        S1       Senior Staff Band 3   

     Age  Score   Phone_Number Domicile_Province  
163   49   4.07  6285246994109       DKI Jakarta  
53    37   4.54  6285247960462       DKI Jakarta  
20    49   3.96   628315232935              Bali  
721   38   4.07  6285246731907        Jawa Barat  
287   29   3.66  6285247310009       DKI Jakarta  
809   38   3.89  6285247523434        Jawa Barat  
409   32   3.55  6285247528205     DI Yogyakarta  
723   35   4.22  6285246990036        Jawa Barat  
107   39   4.23  6285247348227        Jawa Barat  
561   25   4.39  6285246720852        Jawa Barat

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Employee_Id        930 non-null    int64  
 1   Name               930 non-null    object 
 2   Gender             930 non-null    object 
 3   Edu_Level          930 non-null    object 
 4   Job_Category       930 non-null    object 
 5   Age                930 non-null    int64  
 6   Score              930 non-null    float64
 7   Phone_Number       930 non-null    int64  
 8   Domicile_Province  930 non-null    object 
dtypes: float64(1), int64(3), object(5)
memory usage: 65.5+ KB


In [36]:
data.to_excel("D:\Kerja\Dattabot\dataset_clean.xlsx")